theme: jekyll-theme-hacker
tittle: Hacker Box blog.
description: Este es mi blog personalizado donde te podré contar todo lo que voy aprendiendo y como tu tambien puedes hacer magia en el mundo real con estos conocimientos.
